const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openUrl: (url, closeAfter) => ipcRenderer.send('open-url', url, closeAfter),
  openPath: (folder, closeAfter) => ipcRenderer.send('open-path', folder, closeAfter),
  copyText: (text, closeAfter) => ipcRenderer.send('copy-text', text, closeAfter),
  hideApp: () => ipcRenderer.send('hide-app'),
  setOpacity: (opacity) => ipcRenderer.send('set-opacity', opacity),
  getOpenWindows: () => ipcRenderer.invoke('get-open-windows'),
  focusWindow: (title, closeAfter) => ipcRenderer.invoke('focus-window', title, closeAfter),
  launchOrFocusApp: (exePath, closeAfter, monitor) => ipcRenderer.invoke('launch-or-focus-app', exePath, closeAfter, monitor),
  updateShortcut: (shortcut) => ipcRenderer.send('update-shortcut', shortcut),
  detectDialog: () => ipcRenderer.invoke('detect-dialog'),
  jumpToDialogFolder: (folderPath) => ipcRenderer.send('jump-to-dialog-folder', folderPath),
  storeLoad: () => ipcRenderer.invoke('store-load'),
  storeSave: (data) => ipcRenderer.invoke('store-save', data),
  getWindowPosition: () => ipcRenderer.invoke('get-window-position'),
  moveWindow: (x, y) => ipcRenderer.send('window-move', x, y),
  exportData: () => ipcRenderer.invoke('export-data'),
  importData: () => ipcRenderer.invoke('import-data'),
  runCmd: (command, closeAfter) => ipcRenderer.send('run-cmd', command, closeAfter),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  pickExe: () => ipcRenderer.invoke('pick-exe'),
  getFileIcon: (filePath) => ipcRenderer.invoke('get-file-icon', filePath),
  getExtensionBridgeStatus: () => ipcRenderer.invoke('get-extension-bridge-status'),
  openExtensionInstallHelper: (targetBrowser) => ipcRenderer.invoke('open-extension-install-helper', targetBrowser),
  tileWindows: (items) => ipcRenderer.invoke('tile-windows', items),
  maximizeWindow: (item) => ipcRenderer.invoke('maximize-window', item),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  installUpdate: () => ipcRenderer.send('install-update'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_, info) => cb(info)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_, info) => cb(info)),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  checkWindowsAlive: (titles) => ipcRenderer.invoke('check-windows-alive', titles),
  checkFileExists: (filePath) => ipcRenderer.invoke('check-file-exists', filePath),
  checkItemsForTile: (items) => ipcRenderer.invoke('check-items-for-tile', items),
  launchItemsForTile: (items) => ipcRenderer.invoke('launch-items-for-tile', items),
  runTilePs: (args) => ipcRenderer.invoke('run-tile-ps', args),
  snapWindow: (item, zone) => ipcRenderer.invoke('snap-window', { item, zone }),
  resizeActiveWindow: (pct) => ipcRenderer.invoke('resize-active-window', { pct }),
  getMonitors: () => ipcRenderer.invoke('get-monitors'),
  identifyMonitors: () => ipcRenderer.invoke('identify-monitors'),
  openGuide: () => ipcRenderer.send('open-guide'),
  signalReady: () => ipcRenderer.send('renderer-ready'),
  setLoadingStatus: (msg) => ipcRenderer.send('set-loading-status', msg),
});
